import { defineConfig } from "vocs";

export default defineConfig({
	title: "Sequoia",
	description: "Publish evergreen to the ATmosphere",
	baseUrl: "https://sequoia.pub",
	iconUrl: {
		light: "/icon-light.png",
		dark: "/icon-dark.png",
	},
	ogImageUrl: "/og.png",
	aiCta: false,
	editLink: {
		pattern: "https://tangled.org/stevedylan.dev/sequoia",
		text: "Edit on Tangled",
	},
	topNav: [
		{ text: "Docs", link: "/quickstart", match: "/" },
		{ text: "Blog", link: "/blog" },
		{ text: "Tangled", link: "https://tangled.org/stevedylan.dev/sequoia" },
		{ text: "GitHub", link: "https://github.com/stevedylandev/sequoia" },
	],
	sidebar: [
		{
			text: "Introduction",
			items: [
				{ text: "Quickstart", link: "/quickstart" },
				{ text: "What is Sequoia?", link: "/what-is-sequoia" },
				{ text: "Supported Frameworks", link: "/supported-frameworks" },
			],
		},
		{
			text: "Guides",
			items: [
				{ text: "Setup", link: "/setup" },
				{ text: "Publishing", link: "/publishing" },
				{ text: "Comments", link: "/comments" },
				{ text: "Verifying", link: "/verifying" },
				{ text: "Workflows", link: "/workflows" },
			],
		},
		{
			text: "Reference",
			items: [
				{ text: "CLI", link: "/cli-reference" },
				{ text: "Config", link: "/config" },
			],
		},
	],
	font: {
		google: "Josefin Sans",
	},
	markdown: {
		code: {
			themes: {
				light: "vitesse-light",
				dark: "vitesse-dark",
			},
		},
	},
	theme: {
		accentColor: "#3A5A40",
		variables: {
			color: {
				background: { light: "#F5F3EF", dark: "#1A1A1A" },
				background2: { light: "#EDEAE4", dark: "#242424" },
				background3: { light: "#E5E2DB", dark: "#2E2E2E" },
				background4: { light: "#DDD9D1", dark: "#383838" },
				background5: { light: "#D5D1C8", dark: "#424242" },
				backgroundAccent: { light: "#3A5A40", dark: "#4A7055" },
				backgroundAccentHover: { light: "#2E4832", dark: "#5A8065" },
				backgroundAccentText: { light: "#FFFFFF", dark: "#FFFFFF" },
				backgroundDark: { light: "#EDEAE4", dark: "#141414" },
				text: { light: "#2C2C2C", dark: "#E5E5E5" },
				text2: { light: "#4A4A4A", dark: "#C5C5C5" },
				text3: { light: "#6B6B6B", dark: "#A5A5A5" },
				text4: { light: "#8B7355", dark: "#A59077" },
				heading: { light: "#2C2C2C", dark: "#F5F3EF" },
				textAccent: { light: "#3A5A40", dark: "#5A9070" },
				textAccentHover: { light: "#2E4832", dark: "#6AA080" },
				border: { light: "#D5D1C8", dark: "#3A3A3A" },
				border2: { light: "#8B7355", dark: "#6B5A42" },
				borderAccent: { light: "#3A5A40", dark: "#5A9070" },
				link: { light: "#3A5A40", dark: "#5A9070" },
				linkHover: { light: "#2E4832", dark: "#6AA080" },
				infoBackground: { light: "#E8F0F5", dark: "#1A2A35" },
				infoBorder: { light: "#5B8FA8", dark: "#4A7A8F" },
				infoText: { light: "#3A6B85", dark: "#7AB5D5" },
				infoTextHover: { light: "#2E5569", dark: "#8AC5E5" },
				successBackground: { light: "#E8F0E9", dark: "#1A2A1E" },
				successBorder: { light: "#3A5A40", dark: "#5A9070" },
				successText: { light: "#3A5A40", dark: "#6AA080" },
				successTextHover: { light: "#2E4832", dark: "#7AB090" },
				tipBackground: { light: "#E8F0E9", dark: "#1A2A1E" },
				tipBorder: { light: "#3A5A40", dark: "#5A9070" },
				tipText: { light: "#3A5A40", dark: "#6AA080" },
				tipTextHover: { light: "#2E4832", dark: "#7AB090" },
				warningBackground: { light: "#F5F0E5", dark: "#2A2418" },
				warningBorder: { light: "#8B7355", dark: "#A59077" },
				warningText: { light: "#6B5A42", dark: "#C5B097" },
				warningTextHover: { light: "#5A4A35", dark: "#D5C0A7" },
				dangerBackground: { light: "#F5E8E8", dark: "#2A1A1A" },
				dangerBorder: { light: "#A85B5B", dark: "#C87B7B" },
				dangerText: { light: "#8B3A3A", dark: "#E89B9B" },
				dangerTextHover: { light: "#6B2E2E", dark: "#F8ABAB" },
				noteBackground: { light: "#EDEAE4", dark: "#242424" },
				noteBorder: { light: "#8B7355", dark: "#A59077" },
				noteText: { light: "#4A4A4A", dark: "#C5C5C5" },
				blockquoteBorder: { light: "#8B7355", dark: "#A59077" },
				blockquoteText: { light: "#4A4A4A", dark: "#C5C5C5" },
				tableBorder: { light: "#D5D1C8", dark: "#3A3A3A" },
				tableHeaderBackground: { light: "#EDEAE4", dark: "#2E2E2E" },
				tableHeaderText: { light: "#2C2C2C", dark: "#E5E5E5" },
				hr: { light: "#D5D1C8", dark: "#3A3A3A" },
				shadow: { light: "rgba(44, 44, 44, 0.1)", dark: "rgba(0, 0, 0, 0.3)" },
				white: { light: "#FFFFFF", dark: "#FFFFFF" },
				black: { light: "#2C2C2C", dark: "#1A1A1A" },
			},
		},
	},
});
