import { defineConfig } from "vocs";

export default defineConfig({
	title: "Sequoia",
	description: "Publish evergreen to the ATmosphere",
	baseUrl: "https://sequoia.pub",
	iconUrl: "/icon.png",
	ogImageUrl: "/og.png",
	aiCta: false,
	editLink: {
		pattern: "https://leaflet.org/stevedylan.dev",
		text: "Edit on Tangled",
	},
	topNav: [
		{ text: "Docs", link: "/quickstart", match: "/" },
		{ text: "Blog", link: "/blog" },
		{ text: "Tanlged", link: "https://tangled.org" },
		{ text: "GitHub", link: "https://github.com" },
	],
	sidebar: [
		{
			text: "Introduction",
			items: [
				{ text: "Quickstart", link: "/quickstart" },
				{ text: "What is Sequoia?", link: "/what-is-sequoia" },
				{ text: "Supported Frameworks", link: "/supported-frameworks" },
			],
		},
		{
			text: "Guides",
			items: [
				{ text: "Setup", link: "/setup" },
				{ text: "Publishing", link: "/publishing" },
				{ text: "Verifying", link: "/verifying" },
				{ text: "Workflows", link: "/workflows" },
			],
		},
		{
			text: "Reference",
			items: [
				{ text: "CLI", link: "/cli-reference" },
				{ text: "Config", link: "/config" },
			],
		},
	],
	font: {
		google: "Josefin Sans",
	},
	markdown: {
		code: {
			themes: {
				light: "vitesse-light",
			},
		},
	},
	theme: {
		colorScheme: "light",
		accentColor: "#3A5A40",
		variables: {
			color: {
				background: "#F5F3EF",
				background2: "#EDEAE4",
				background3: "#E5E2DB",
				background4: "#DDD9D1",
				background5: "#D5D1C8",
				backgroundAccent: "#3A5A40",
				backgroundAccentHover: "#2E4832",
				backgroundAccentText: "#FFFFFF",
				backgroundDark: "#EDEAE4",
				text: "#2C2C2C",
				text2: "#4A4A4A",
				text3: "#6B6B6B",
				text4: "#8B7355",
				heading: "#2C2C2C",
				textAccent: "#3A5A40",
				textAccentHover: "#2E4832",
				border: "#D5D1C8",
				border2: "#8B7355",
				borderAccent: "#3A5A40",
				link: "#3A5A40",
				linkHover: "#2E4832",
				infoBackground: "#E8F0F5",
				infoBorder: "#5B8FA8",
				infoText: "#3A6B85",
				infoTextHover: "#2E5569",
				successBackground: "#E8F0E9",
				successBorder: "#3A5A40",
				successText: "#3A5A40",
				successTextHover: "#2E4832",
				tipBackground: "#E8F0E9",
				tipBorder: "#3A5A40",
				tipText: "#3A5A40",
				tipTextHover: "#2E4832",
				warningBackground: "#F5F0E5",
				warningBorder: "#8B7355",
				warningText: "#6B5A42",
				warningTextHover: "#5A4A35",
				dangerBackground: "#F5E8E8",
				dangerBorder: "#A85B5B",
				dangerText: "#8B3A3A",
				dangerTextHover: "#6B2E2E",
				noteBackground: "#EDEAE4",
				noteBorder: "#8B7355",
				noteText: "#4A4A4A",
				blockquoteBorder: "#8B7355",
				blockquoteText: "#4A4A4A",
				tableBorder: "#D5D1C8",
				tableHeaderBackground: "#EDEAE4",
				tableHeaderText: "#2C2C2C",
				hr: "#D5D1C8",
				shadow: "rgba(44, 44, 44, 0.1)",
				white: "#FFFFFF",
				black: "#2C2C2C",
			},
		},
	},
});
